### ISSUE TITLE
.ps modifier

### ISSUE THREAD

**Issue by bkane2** [genelkim/ulf-lib#8]
For sentences like "where was the Twitter block right before I moved it", we need to modify the sentential preposition, i.e.

`(right.mod-a (before.ps (i.pro ((past move.v) it.pro))))`

The ULF code currently doesn't support the mod-a in that position.

**Comment by genelkim** [comment]
I implemented a change to handle this in the ttt-based type system code in this pull request https://github.com/genelkim/ulf-lib/pull/15. This should be enough for this to be handled correctly in ulf2english and ulf-pragmatics.

I've added tests for what it would look like for this to work in the formal type composition system. If you need it working there too, I can try to find time to get it working in that this week too. This will take a bit of effort since this sort of crosses the boundary between the ULF and EL type systems, which are not quite the same.

**Comment by genelkim** [comment]
Handled fully in https://github.com/genelkim/ulf-lib/pull/54. This will be merged to master fairly soon (~a week). I also introduced issue https://github.com/genelkim/ulf-lib/issues/53 for a more nuanced handling with a new type `mod-p`.
